[phases.build]
cmds = [
  "echo 'DEBUG: Build phase running!'",
  "ls -l",
  "npm install -g typescript",
  "npm ci",
  "ls -l src",
  "false", // This will always fail and should show up in the logs
  "tsc",
  "ls -l dist"
]

[phases.start]
cmds = ["node dist/app.js"]
