[phases.build]
cmds = [
  "exit 1",
  "echo 'HELLO FROM NIXPACKS BUILD PHASE'",
  "ls -l",
  "npm install -g typescript",
  "npm ci",
  "ls -l src",
  "tsc",
  "ls -l dist"
]

[phases.start]
cmds = ["node dist/app.js"]
